// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoY1aDWwrUwOIvlGJeYs9T7F2yPCLiACA',
    appId: '1:780565131672:web:f819b285983173576a3bed',
    messagingSenderId: '780565131672',
    projectId: 'movie-app-dicoding',
    authDomain: 'movie-app-dicoding.firebaseapp.com',
    storageBucket: 'movie-app-dicoding.firebasestorage.app',
    measurementId: 'G-293TGFXN8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdpeswmIlAqmAlxgQaQxpM3MA-6R27ps',
    appId: '1:780565131672:android:0ab9af7d58ba17836a3bed',
    messagingSenderId: '780565131672',
    projectId: 'movie-app-dicoding',
    storageBucket: 'movie-app-dicoding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15xlcV2YjauEnq9tKzs8I6d7X3jVmguQ',
    appId: '1:780565131672:ios:d95a6feb09fb6d426a3bed',
    messagingSenderId: '780565131672',
    projectId: 'movie-app-dicoding',
    storageBucket: 'movie-app-dicoding.firebasestorage.app',
    iosBundleId: 'com.example.movieAppDicoding',
  );
}
