// Mocks generated by Mockito 5.4.6 from annotations
// in movie_app_dicoding/test/data/repositories/tv_series_repository_impl_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app_dicoding/data/datasources/tv_series_local_data_source.dart'
    as _i7;
import 'package:movie_app_dicoding/data/datasources/tv_series_remote_data_source.dart'
    as _i3;
import 'package:movie_app_dicoding/data/models/episode_model.dart' as _i6;
import 'package:movie_app_dicoding/data/models/tv_series_detail_model.dart'
    as _i2;
import 'package:movie_app_dicoding/data/models/tv_series_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesDetailModel_0 extends _i1.SmartFake
    implements _i2.TvSeriesDetailModel {
  _FakeTvSeriesDetailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<_i2.TvSeriesDetailModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i4.Future<_i2.TvSeriesDetailModel>.value(
              _FakeTvSeriesDetailModel_0(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.TvSeriesDetailModel>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i6.EpisodeModel>> getSeasonEpisodes(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonEpisodes, [tvId, seasonNumber]),
            returnValue: _i4.Future<List<_i6.EpisodeModel>>.value(
              <_i6.EpisodeModel>[],
            ),
          )
          as _i4.Future<List<_i6.EpisodeModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i7.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> addToWatchlist(_i2.TvSeriesDetailModel? tvSeriesDetail) =>
      (super.noSuchMethod(
            Invocation.method(#addToWatchlist, [tvSeriesDetail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
