// Mocks generated by Mockito 5.4.6 from annotations
// in movie_app_dicoding/test/domain/usecases/tv_series_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app_dicoding/domain/entities/episode.dart' as _i6;
import 'package:movie_app_dicoding/domain/entities/tv_series.dart' as _i5;
import 'package:movie_app_dicoding/domain/entities/tv_series_detail.dart'
    as _i2;
import 'package:movie_app_dicoding/domain/repositories/tv_series_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.TvSeriesDetail {
  _FakeTvSeriesDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i3.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TvSeries>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<List<_i5.TvSeries>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<List<_i5.TvSeries>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<_i2.TvSeriesDetail> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i4.Future<_i2.TvSeriesDetail>.value(
              _FakeTvSeriesDetail_0(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.TvSeriesDetail>);

  @override
  _i4.Future<List<_i5.TvSeries>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<List<_i5.TvSeries>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<void> addToWatchlist(_i2.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
            Invocation.method(#addToWatchlist, [tvSeriesDetail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TvSeries>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i4.Future<List<_i5.TvSeries>>.value(<_i5.TvSeries>[]),
          )
          as _i4.Future<List<_i5.TvSeries>>);

  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i6.Episode>> getSeasonEpisodes(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonEpisodes, [tvId, seasonNumber]),
            returnValue: _i4.Future<List<_i6.Episode>>.value(<_i6.Episode>[]),
          )
          as _i4.Future<List<_i6.Episode>>);
}
